# Generated by Django 5.0.6 on 2024-09-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profileImage/no_profile.png', upload_to='profileImage'),
        ),
    ]
