# Generated by Django 5.1.1 on 2024-09-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=300)),
                ('Phone', models.CharField(blank=True, max_length=14, null=True)),
                ('Subject', models.CharField(max_length=300)),
                ('Message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'ContactInfos',
            },
        ),
    ]
