# Generated by Django 5.1.1 on 2024-09-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Image', models.ImageField(upload_to='media')),
                ('Price', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Banner',
            },
        ),
    ]
