# Generated by Django 5.1.1 on 2024-09-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='dis_price',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='product_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
