# Generated by Django 5.0.6 on 2024-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_brand_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptions',
            field=models.TextField(null=True),
        ),
    ]
